// src/Redux/userConstants.ts

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAIL = 'SOCIAL_LOGIN_FAIL';
export const SOCIAL_LOGIN_RESET = 'SOCIAL_LOGIN_RESET';


export const USER_INDIVIDUAL_REQUEST = 'USER_INDIVIDUAL_REQUEST';
export const USER_INDIVIDUAL_SUCCESS = 'USER_INDIVIDUAL_SUCCESS';
export const USER_INDIVIDUAL_FAIL = 'USER_INDIVIDUAL_FAIL';
export const USER_INDIVIDUAL_RESET = 'USER_INDIVIDUAL_RESET';

export const USER_UPDATE_ONLINE_STATUS = 'USER_UPDATE_ONLINE_STATUS';